//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace challengexpandit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public int contactId { get; set; }
        public int contactType { get; set; }
        public string contactNumber { get; set; }
        public System.DateTime createdOn { get; set; }
        public string createdBy { get; set; }
        public System.DateTime updatedOn { get; set; }
        public string updatedBy { get; set; }
        public int personId { get; set; }
    
        public virtual Persons Persons { get; set; }
    }
}
