//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace challengexpanditV1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Persons
    {
        [Key]
        public int personId { get; set; }

       // [Display(Name ="Name", AutoGenerateFilter = true)]
       // [Required(ErrorMessage = "Campo obrigatório")]
        public string name { get; set; }

        [Display(Name = "Morada")]
        public string address { get; set; }

        [Display(Name = "Código Postal")]
        [RegularExpression(@"^\d{4}(-\d{3})?$", ErrorMessage = "Código Postal Inválido")]
        public string zipCode { get; set; }

        [Display(Name = "Cidade")]
        public string city { get; set; }

        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage ="Email inválido")]
        public string email { get; set; }

        [Display(Name = "Fotografia")]
        public byte[] photo { get; set; }

        [Display(Name = "Telemóvel")]
        public string mobileNumber { get; set; }

        [Display(Name = "Casa")]
        public string homeNumber { get; set; }

        [Display(Name = "Trabalho")]
        public string officeNumber { get; set; }

        [Display(Name = "Outro")]
        public string otherNumber { get; set; }
 
        public System.DateTime createdOn { get; set; }
        public string createdBy { get; set; }
        public System.DateTime updatedOn { get; set; }
        public string updatedBy { get; set; }
    }
}
